spring: 
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: SimMS
          uri: lb://SimMS
          predicates:
            - Path=/SIMDetail/**
        - id: CustomerMS
          uri: lb://CustomerMS
          predicates:
            - Path=/Customer*
         
      
